[package]
name = "rollbar-java-agent"
version = "0.1.0"
authors = ["Andrew Weiss <wvvwwvw@gmail.com>"]
edition = "2018"

[lib]
crate_type = [ "cdylib" ]

[dependencies]
pretty_env_logger = "0.2.5"
log = "0.4"
rollbar-jvm = { path = "../jvm_core" }
